######################################################################
# Automatically generated by qmake (3.0) Thu Feb 4 06:32:16 2016
######################################################################
QT += core gui 

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
